/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Serene Ledger design tokens
        'inverse-primary': '#a6d0b9',
        'surface-container': '#f2efd0',
        'surface': '#fefbdb',
        'primary-container': '#0a3323',
        'surface-container-high': '#ece9cb',
        'primary-fixed-dim': '#a6d0b9',
        'tertiary': '#101b00',
        'tertiary-fixed': '#d3eca2',
        'on-secondary': '#ffffff',
        'outline': '#717973',
        'surface-tint': '#406653',
        'on-primary-fixed-variant': '#284e3c',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#eab9d2',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#213100',
        'on-secondary-container': '#7a5369',
        'surface-bright': '#fefbdb',
        'secondary-fixed': '#ffd8eb',
        'secondary-container': '#fecce6',
        'outline-variant': '#c1c8c2',
        'on-error': '#ffffff',
        'background': '#fefbdb',
        'tertiary-fixed-dim': '#b8cf88',
        'on-primary': '#ffffff',
        'error': '#ba1a1a',
        'secondary': '#7a5369',
        'primary': '#001d11',
        'on-error-container': '#93000a',
        'on-surface-variant': '#414844',
        'on-primary-fixed': '#002114',
        'surface-container-low': '#f8f5d6',
        'on-surface': '#1d1c0a',
        'on-secondary-fixed': '#2f1124',
        'error-container': '#ffdad6',
        'surface-variant': '#e7e4c5',
        'on-tertiary-fixed-variant': '#3a4d15',
        'on-tertiary-fixed': '#141f00',
        'on-tertiary-container': '#859b5a',
        'surface-container-highest': '#e7e4c5',
        'on-primary-container': '#749d87',
        'surface-dim': '#dedbbd',
        'on-secondary-fixed-variant': '#603b51',
        'on-background': '#1d1c0a',
        'primary-fixed': '#c2ecd4',
        'inverse-surface': '#32311d',
        'inverse-on-surface': '#f5f2d3',
        'pantone-686': '#D0A1BA',
      },
      spacing: {
        'xl': '80px',
        'sm': '12px',
        'gutter': '20px',
        'container-max': '1200px',
        'md': '24px',
        'lg': '48px',
        'base': '8px',
        'xs': '4px',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          '"SF Pro Display"',
          'system-ui',
          'sans-serif',
        ],
        'headline-md': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', 'system-ui', 'sans-serif'],
        'display-lg': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', 'system-ui', 'sans-serif'],
        'body-lg': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', 'system-ui', 'sans-serif'],
        'label-md': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', 'system-ui', 'sans-serif'],
        'display-lg-mobile': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', 'system-ui', 'sans-serif'],
        'body-sm': ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Text"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['17px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
