/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#f3b5ca",
        "surface-container": "#f2efd0",
        "surface": "#fefbdb",
        "primary-container": "#C85A7E",
        "surface-container-high": "#ece9cb",
        "primary-fixed-dim": "#f3b5ca",
        "tertiary": "#2e0018",
        "tertiary-fixed": "#ffd8e7",
        "on-secondary": "#ffffff",
        "outline": "#7e7277",
        "surface-tint": "#E47A9D",
        "on-primary-fixed-variant": "#8C3252",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#eab9d2",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4a0028",
        "on-secondary-container": "#7a5369",
        "surface-bright": "#fefbdb",
        "secondary-fixed": "#ffd8eb",
        "secondary-container": "#fecce6",
        "outline-variant": "#c8bece",
        "on-error": "#ffffff",
        "background": "#fefbdb",
        "tertiary-fixed-dim": "#f8b2cb",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "secondary": "#7a5369",
        "primary": "#8C3252",
        "on-error-container": "#93000a",
        "on-surface-variant": "#544349",
        "on-primary-fixed": "#3d001e",
        "surface-container-low": "#f8f5d6",
        "on-surface": "#1d1c0a",
        "on-secondary-fixed": "#2f1124",
        "error-container": "#ffdad6",
        "surface-variant": "#e7e4c5",
        "on-tertiary-fixed-variant": "#6b1a3e",
        "on-tertiary-fixed": "#35001d",
        "on-tertiary-container": "#e47a9d",
        "surface-container-highest": "#e7e4c5",
        "on-primary-container": "#E47A9D",
        "surface-dim": "#dedbbd",
        "on-secondary-fixed-variant": "#603b51",
        "on-background": "#1d1c0a",
        "primary-fixed": "#ffd8e7",
        "inverse-surface": "#32311d",
        "inverse-on-surface": "#f5f2d3",
        "pantone-686": "#E47A9D",
        "pink-carnation": "#E47A9D"
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Display"',
          '"SF Pro Text"',
          "system-ui",
          "sans-serif",
        ],
      },
    },
  },
  plugins: [],
};
